<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "oauth2_server"
 *
 * Auto generated by Extension Builder 2020-12-08
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'OAuth2 Server',
    'description' => '',
    'category' => 'fe',
    'author' => '',
    'author_email' => '',
    'state' => 'beta',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.4.0-10.4.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
