base: 'https://typo3-oauth2-server.ddev.site/'
errorHandling: {  }
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
routes: {  }
oauth2:
  accessTokensExpireIn: 'P10Y'
  loginPageUid: 1
  consentPageUid: 4
  scopes:
    - api
    - { identifier: read, description: 'Read access', consent: true }
    - { identifier: write, description: 'Write access', consent: true }
