base: 'https://typo3-oauth2-server.ddev.site/'
dependencies:
  - oauth2-server/identity-provider
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: ''
